#dist: trusty
sudo: false
language: java
services: docker
addons:
  hosts:
    - mariadb.example.com

before_install:
  - chmod +x .travis/script.sh
install:
  - export PROJ_PATH=`pwd`
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql

matrix:
  include:
    - env: DB=mariadb:10.3
      jdk: oraclejdk10

script:
  - .travis/script.sh
