#dist: trusty
sudo: false
language: java
services: docker
addons:
  hosts:
    - mariadb.example.com

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - env: DB=mariadb:10.2
      jdk: oraclejdk10

script:
  - .travis/script.sh
