#dist: trusty
sudo: false
language: java
services: docker
jdk: oraclejdk10

addons:
  hosts:
    - mariadb.example.com

before_install:
  - chmod +x .travis/script.sh
install:
  - export PROJ_PATH=`pwd`
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql

matrix:
  include:
    - bench: Do_1
    - bench: Create_and_close_Connection
    - bench: Select_1
    - bench: Select_1_mysql_user
    - bench: Select_10_cols_from_seq_1_to_100000

script:
  - .travis/script.sh
