#dist: trusty
sudo: false
language: java
services: docker
jdk: openjdk11

addons:
  hosts:
    - mariadb.example.com

before_install:
  - chmod +x .travis/script.sh
install:
  - export PROJ_PATH=`pwd`
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql

matrix:
  include:
    - env: bench=Do_1
    - env: bench=Create_and_close_Connection
    - env: bench=Select_1
    - env: bench=Select_1_mysql_user
    - env: bench=Select_10_cols_from_seq_1_to_100000

script:
  - .travis/script.sh
