version: '2.1'
services:
  db:
    image: $DB
    command: --max-connections=5000 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
    ports:
      - 3305:3306
    volumes:
      - $ENTRYPOINT:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: testj
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
